### ISSUE TITLE
Syllabus Module 2 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-511-programming-in-python#15]
Can we please discuss the syllabus before I work on the second module ? Thank you!

Find the doc [here](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/blob/master/docs/syllabus-learning-outcomes.md)

**Comment by mgelbart** [comment]
Module 2 [here](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/blob/master/docs/syllabus-learning-outcomes.md#module-2-not-so-scary-wrangling-table-manipulation-and-chaining).

Comments:

- the first 3 topics look very overlapping with module 1. Can we make the distinction more clear?
- first learning outcome - wasn't that in module 1?
- regarding creating new columns, I recently learned that the preferred way of creating a new columns may be to use [`df.assign`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html) rather than `[]`. This helps deal with the set-with-copy-warning. 
- `sort_values` also already covered in module 1?
- I would mentioned `groupby` in the learning goal. 

The rest looks good to me. I have a nice example for combining `groupby` and `sort_values` if you're looking for one, based on [this avocado prices example](https://www.kaggle.com/neuromusic/avocado-prices). Let me know if you want to see it.

**Comment by ttimbers** [comment]
OK, I have thought a lot more about this, and I think I would reorganize the remaining Pandas topics in this order (grouping more similar concepts/tasks together):

### Module 2: Not So Scary Wrangling (Table Manipulation and Chaining)

#### Topics 

- Read different  files using Pandas `pd.read_csv()` and other functions
- Simple dataframe manipulations and operations  **what are you referring to here?**
- filtering using `df[]` ~~and introduce `df.query()` notation~~ **remove `query` or make it optional**
- Chaining 
- `df.grouby()` and `df.agg()` 
- Modify values in a dataframe using `df.apply()` and `df.applymap()` **(I see this fit under the topic of iteration - so I think it pairs well with `df.grouby()` and `df.agg()`)** 


### Module 3: It's Tidy up time! (Tidy Data)

#### Topics 

- Tidy data - what is it?
- Manipulating data using `df.melt()` and `df.pivot()`
- Dataframe stacking and unstacking 
- Combining dataframes 

### Module 4: Handling other advanced(?) data formats and missing & erroneous values

#### Topics 
- Working with DateTime format 
- Working with strings in dataframes ? regex??? (Mike suggestion)
- Identifying and handling missing/erroneous values 
- Pandas profiling

**Comment by hfboyce** [comment]
> - Simple dataframe manipulations and operations  **what are you referring to here?**

Things like new columns and  renaming column names
I initially was also going to put in `sort_values()`  but that is now in Module 1. 

I do like the changes you suggested but we should discuss where `df.apply()` and `df.applymap()` should live.

**Comment by hfboyce** [comment]
>  I have a nice example for combining groupby and sort_values if you're looking for one, based on this avocado prices example. Let me know if you want to see it. It involves datatimes but basically just setting parse_dates in read_csv and not much else about datetimes needed.

I absolutely want to see! :)

**Comment by mgelbart** [comment]
@hfboyce I uploaded it to this repo [here](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/blob/master/junk/hw7.ipynb). Check out Exercise 1(b) specifically. It is sort of like scavenger hunts inside the dataset. You could imagine asking them to find the exact regions/dates that are missing. Although it might be on the challenging side for this MCL course.
