### ISSUE TITLE
Feedback Take 2

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-511-programming-in-python#16]
[Netlify Site link](https://mcl-dsci-511-programming-in-python.netlify.com/module1)

- I _think_ I've added all the changes we discussed. 
- I added a small part on csv files and the difference between functions/modules and attributes as per last meeting. 
- I ran Grammarly and spellcheck on this too so hopefully this picks up _most_ of my mistakes. 
- There are quite a few changes from when you last saw this so hopefully it's been improved substantially. 

For feedback feel free to reference the "exercises" number - be it slide or code/question problem. Also we have slide numbers to reference as well. 

Please let me know of any concerns!

**Comment by mgelbart** [comment]
- 1.2: excel -> Excel
- did you introduce comments somewhere before the first code exercise?
- 1.8: need to close quotation marks
- 1.9: missing periods. Also, "Another important method to know is what if we don’t want to output the whole table" -> "What if we don't want to output the whole table?"
- 1.9: brackets -> parentheses?
- 3: should we explain the `data/`? Some of them might never have used a command line so will not know about `/` for paths. 
- 5.3 "Let’s import pandas and bring in our dataset named cereal.csv using the name of the candy bar as the index like we did last time with index_col=0." is confusing why it's talking about candy bars. 
- 5.4 "We can see 7 of the 15 columns of the dataframe and the first 5 rows of the data" no longer true with the horizontal scrolling?
- 5.4 I see you're trying to cover your bases, but nonetheless I'd delete " In other cases, the index label could be named with a number."
- 5.6 this is one of those cases where it'd be really helpful to see the table while reading that text.
- 5.7 and several other places (5.9, etc): I think we should say "Here's the code that does this:"  or something like that. The code feels a bit abrupt.
- 5.8 and likewise here, I'd say "Let's take a closer look at our line of code"
- 5.9 need quotation marks for row-name-start and row-name-end.
- 6.1: "That's correct! Good job! This has both loc and “quotation” which are both needed to slice here." but shouldn't it say "both loc and a colon (:)" ? Do we even need a message, actually, other than "That's correct! Good job!" ?
- 6.2: I got this wrong at first. I was slightly confused by how the df is printed out, with no indication that name is the index. could we move "name" lower down like how it usually prints?
- 10: capitalization of "L" in "Let’s answer some slicing questions."
- 13.4: "Selecting the column type would be as simple as so:" - typo
- 15: `penalty players` -> `penalty_players`
- 16.6: should we say something about why, so it doesn't seem insane? Maybe say that for `[2:6]` we have 6-2=4 and so we get back 4 things?
- 16.9: "numeric" -> "integers, and not in quotation marks" ?
- 16.10: something is wrong here - the numbers in the recap don't match those in the code.
- 17: there's no need to look at the columns to answer these questions
- 18: `index_loc=0` -> `index_col=0` ?
- 18: isn't that only easier if we first print out the df? or do you expect them to do that? Same for 19.
- 20.4: "it's" -> "its",   describe -> `describe`
- 20.6 "You can make change". But actually I'd rewrite that whole sentence. Something is missing here. I think first, before this slide, we need to talk about numeric vs. categorical columns. And then explain that by default `describe` only showed the numeric ones. And _then_ talk about `include='all'`. We need these definitions later on anyway, e.g. 20.9 refers to categorical columns.
- 20.8: Capital "y"
- 20.8: they might be wondering why you aren't using double square brackets when grabbing a single column. But also, here, why not just show them `df.sum()` and `df.median()` instead?
- they might not now what a frequency table is. Maybe show the frequency table first and then talk about it?
- 20.11: I don't remember exactly, but didn't we agree to drop `pd.DataFrame` ?
- 20.13: "need to be set equal to" typo
- 21.1: I would delete or modify this. It is confusing that none of the answers involve `value_counts` Also, in the question it says `pd.value_counts` but we aren't using the `pd` right?

**Comment by mgelbart** [comment]
Hmm... I think I was reviewing an older version of your work?! I pressed "refresh" on my browser and now everything is different. Did my browser load up a cached version the first time, or something?

**Comment by hfboyce** [comment]
It definitely could have been the case. 
My version 2.0 should have 31 sections and I definitely dropped a bunch of stuff that you mentioned like `pd.DataFrame ` and I have a section on comments early on. 
It looks like you only reviewed 21. 
Oh no, now I feel bad that you reviewed the wrong one! I am so sorry.

**Comment by mgelbart** [comment]
The version I reviewed had 24 or 25 exercises I believe. Do you have this reloading issue as well, where you get the old version even if you close the browser tab and go back to the URL?

It's a bit unfortunate, yeah, but not a big deal. I will update my comments at some point to reflect the new version.

**Comment by hfboyce** [comment]
I am constantly refreshing to make sure everything is fitting properly.  I do notice a delay but I've never experienced a cache from an old version. 

I'll see if any of your comments apply to the current version and add them today. 
Uhg I guess the best thing is to refresh a few times beforehand. I can add a comment somewhere for you to find to make sure it's the correct version from here on? Would that work?

**Comment by mgelbart** [comment]
The current version I'm looking at has Exercise 0-32. Is that the right one?

Also, what does the source look like that creates this site? If it looks reasonable, perhaps it would be easier to just review that?

**Comment by hfboyce** [comment]
Yes 32 Exercises. 
The source is file could be a nightmare.
The [root Module 1 file](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/blob/master/chapters/module1.md) will refer to [exercises](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/tree/master/exercises) and [slides](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/tree/master/slides) in other folders. So it could be a lot of jumping around. 
Of course it's whatever is easier for you.

**Comment by mgelbart** [comment]
New comments (on latest version):

- 1.10: need to close quotation marks
- 1.12 I think we should have at least some interactivity before we get to functions vs. attributes, since that's a bit dry.
- 1.12 Do they know what you mean by "argument"
- 1.12 show `read_csv` with the arguments actually in there, if you're referring to the arguments.
- 1.12 "there are different command types called functions, attributes and methods." I wouldn't call them "command types" - maybe you can not give them any name? Also put attributes at the beginning or end since it's the "different" once.
- 2.2 possibly confusing - what do you mean by each variable? each argument?
- 4: should we explain the `data/`? Some of them might never have used a command line so will not know about `/` for paths. 
- 7.1: "That's correct! Good job! This has both loc and “quotation” which are both needed to slice here." but shouldn't it say "both loc and a colon (:)" ? Do we even need a message, actually, other than "That's correct! Good job!" ?
- 7: I was slightly confused by how the df is printed out, with no indication that name is the index. could we move "name" lower down like how it usually prints?
- 10.2: capitalization of "w" 
- 14: `penalty players` -> `penalty_players`
- 16: the results won't print except for the last one, because it's all one cell. what did we decide about this?
- 17.3: "Selecting the column type would be as simple as so:" was a bit confusing, maybe remove "so" ? 
- 19.6: should we say something about why, so it doesn't seem insane? Maybe say that for `[2:6]` we have 6-2=4 and so we get back 4 things?
- 19.9: "numeric" -> "integers, and not in quotation marks" ?
- 19.10: something is wrong here - the numbers in the recap don't match those in the code.
- 20: there's no need to look at the columns to answer these questions
- 21: `index_loc=0` -> `index_col=0` ?
- 23.2: "the tool for that" -> "the verb for that"
- 23.2: maybe pick something other than sugars where the first 5 values aren't all the same? 
- 21: isn't that only easier if we first print out the df? or do you expect them to do that? Same for 19.
- 25.4: "functions" should be "methods",   it's" -> "its",   describe -> `describe`
- 25.6 I think first, before this slide, we need to talk about numeric vs. categorical columns. And then explain that by default `describe` only showed the numeric ones. And _then_ talk about `include='all'`. We need these definitions later on anyway, e.g. 25.9 refers to categorical columns.
- 25.8: Why not just show them `df.sum()` and `df.median()` instead (or in addition)?
- 25.9 they might not now what a frequency table is. Maybe show the frequency table first and then talk about it?
- 25.9 let's be consistent with single vs. double quotes - i think we're going with single?
- 25.10 "parenthesis" should be "square brackets" in 2 places
- 25.11 I would show it with the name there in the parentheses, instead of just saying it. 
- 26.1: I would delete or modify this. It is confusing that none of the answers involve `value_counts` Also, in the question it says `pd.value_counts` but we aren't using the `pd` right?
- 27: missing periods after tasks 
- 28: if we're being careful we shouldn't say using `df.value_counts()` since that method doesn't exist. let's just say using `value_counts()`. 
- 28: "Export positionfreq to a csv named `positionfrequencies.csvusingpd.to_csv()`." the formatting is broken in that line
- 28: I get a warning when I run the code. Can we suppress that? 
- 29.1: "deck of slide" -> "slide deck"
- 29.5: "1 being full intensity." -> "with 1 being full intensity."
- 29.5: `df.plot.scatter(x='sugars',y='calories', alpha= 0.3)` need a space after the comma, no space after the equals. Same on next slides all the way to the end of this exercise. 
- 29.7: "havew"
- 30: capital "L"
- 30: "in exercise 24" maybe just say "earlier" -> try to avoid things that can break easily as we make changes. 
- 30: again, each task should end with a period. these small things go a long way to making the end product look professional. 
- 30: as earlier, the printing doesn't actually work because it's not at the end of the cell  - it should not be included here.  
- 31: punctuation in tasks
- 31: should we explain the "1e6" scale on the y-axis?

This is a big improvement over the earlier version!

**Comment by hfboyce** [comment]
## Module 1 Questions: 

> 1.12 I think we should have at least some interactivity before we get to functions vs. attributes, since that's a bit dry.

I have a question regarding this. I could easily move the exercises up but that gives me a concern that I have them coding without teaching them about comments. And if I add that slide then I don't know where functions/attributes and comments belong now. 

What if I move the exercise regarding the csv format earlier after explaining what a csv is? 

> 4: should we explain the `data/`? Some of them might never have used a command line so will not know about `/` for paths. 

I can add this? What do you recommend? I was worried about giving too much at once. 

> 16: the results won't print except for the last one, because it's all one cell. what did we decide about this?

We discussed this in the meeting that I would explain comments early on so they could comment out subsequent code to see the object print but now I'm worried this is a problem. I don't find it too realistic to have a separate cell for each question. Maybe this is something we should talk about in the meeting. 

> 20: there's no need to look at the columns to answer these questions



> 25.6 I think first, before this slide, we need to talk about numeric vs. categorical columns. And then explain that by default `describe` only showed the numeric ones. And _then_ talk about `include='all'`. We need these definitions later on anyway, e.g. 25.9 refers to categorical columns.

 On it

> 25.8: Why not just show them `df.sum()` and `df.median()` instead (or in addition)?

In your feedback you explained before to just select certain columns to do this on since with `sum()` and string columns they would just append all the character, so I selected specific columns to avoid this. 

> 25.9 they might not now what a frequency table is. Maybe show the frequency table first and then talk about it?

On it 

> 25.11 I would show it with the name there in the parentheses, instead of just saying it. 

Show what? Instead of saying what? The error message?

> [ ] 28: I get a warning when I run the code. Can we suppress that? 

 Oh boy, yes this was a bit of a problem Suppressing it means I would have to add it to the code which the student sees, or I add an addition argument which could open the flood gates to the differences between series and dataframes so I wanted to ask you the best approach here. Which is the lesser of two evils? 

> 30: as earlier, the printing doesn't actually work because it's not at the end of the cell  - it should not be included here.  

See 16 above. 

> 31: should we explain the "1e6" scale on the y-axis?

I can add it? Recommended?

**Comment by mgelbart** [comment]
Let's discuss at today's meeting.
